import { CareerProps } from '../types/careers';

export const CAREERS: CareerProps[] = [
  {
    position: 'Student Staff',
    company: 'UNNES TV',
    logo: '/images/careers/unnestv.jpg',
    location: 'Universitas Negeri Semarang',
    type: 'Full-time',
    start_date: '2025-1-8',
    end_date: null,
    link: 'https://seeru.ae',
    responsibilities: [],
  },
  {
    position: 'Freelance Portir',
    company: 'Jateng Fair 2024',
    logo: '/images/careers/jtf.png',
    location: 'PT. PRPP Perseroda',
    type: 'Full-time',
    start_date: '2024-7-26',
    end_date: '2024-8-10',
    link: 'https://seeru.ae',
    responsibilities: [
      'Memberikan karcis parkir kepada pengendara saat memasuki area parkir.',
      'Membagikan flyer di beberapa titik keramaian.',
      'Melakukan perhitungan keuangan dan memastikan tiket yang terjual tidak selisih.',
      'Melakukan pengarahan kepada pengunjung.',
    ],
  },
  {
    position: 'Director & Ketua Produksi',
    company: 'Film Catatan Akhir Sekolah',
    logo: '/images/careers/rosvo.png',
    location: 'SMAN 11 Semarang',
    type: 'Full-time',
    start_date: '2024-4',
    end_date: '2024-7',
    link: 'https://seeru.ae',
    responsibilities: [
      'Menjadi Director of Photography yang bertugas mengambil semua video termasuk semua isi dari video.',
      'Melakukan perekaman suara yang digunakan untuk monolog dalam video.',
      'Mengedit, mewarnai video serta melakukan penataan ulang suara agar menjadikan hasil akhir yang baik.',
      'Membantu membuat konsep cerita dan menulis konsep cerita dalam bentuk script.',
      'Memastikan semua produksi berjalan sesuai dengan rundown.',
    ],
  },
  {
    position: 'Tim Kreatif',
    company: 'Yearbook 2024',
    logo: '/images/careers/rosvo.png',
    location: 'SMAN 11 Semarang',
    type: 'Full-time',
    start_date: '2023-8',
    end_date: '2024-4',
    link: 'https://seeru.ae',
    responsibilities: [
      'Mengikuti rapat untuk menentukan ide, tema, dan konsep Yearbook meliputi bentuk packaging.',
      'Mengedit dan memperbaiki foto untuk memastikan kualitas terbaik. Mencakup penyesuaian pencahayaan, kontras, dan penghapusan cacat visual.',
      'Berkoordinasi dengan tim yang bertanggung jawab atas pengumpulan informasi dan tulisan untuk memastikan konten sesuai dengan desain visual.',
      'Meninjau seluruh hasil desain buku untuk mengecek kesalahan yang perlu diperbaiki sebelum masuk ke tahap produksi akhir.',
      'Berkoordinasi dengan perwakilan kelas untuk mengecek desain dan layout pada masing-masing kelas untuk memastikan desain dan layout telah sesuai.',
      'Berkoordinasi dengan vendor memastikan semua desain dan isi buku sesuai, serta melakukan quality control sebelum buku dibagikan.',
    ],
  },
];
