import { CareerProps } from '../types/careers';

export const CAREERS: CareerProps[] = [
  {
    position: 'Student Staff',
    company: 'UNNES TV',
    logo: '/images/careers/unnestv.jpg',
    location: 'Universitas Negeri Semarang',
    type: 'Full-time',
    start_date: '2025-1-8',
    end_date: null,
    link: 'https://seeru.ae',
    responsibilities: ['Create video content for the UNNES TV channel.'],
  },
  {
    position: 'Freelance Porter',
    company: 'Jateng Fair 2024',
    logo: '/images/careers/jtf.png',
    location: 'PT. PRPP Perseroda',
    type: 'Full-time',
    start_date: '2024-7-26',
    end_date: '2024-8-10',
    link: 'https://seeru.ae',
    responsibilities: [
      'Provide parking tickets to drivers when entering the parking area.',
      'Distribute flyers at several crowded points.',
      'Perform financial calculations and ensure that the tickets sold do not differ.',
      'Provide directions to visitors.',
    ],
  },
  {
    position: 'Director & Head of Production',
    company: 'Film Catatan Akhir Sekolah',
    logo: '/images/careers/rosvo.png',
    location: 'SMAN 11 Semarang',
    type: 'Full-time',
    start_date: '2024-4',
    end_date: '2024-7',
    link: 'https://seeru.ae',
    responsibilities: [
      'Act as Director of Photography responsible for capturing all videos including all content of the video.',
      'Record sound used for monologues in the video.',
      'Edit, color grade the video, and rearrange the sound to achieve a good final result.',
      'Help create story concepts and write story concepts in script form.',
      'Ensure all production runs according to the rundown.',
    ],
  },
  {
    position: 'Creative Team',
    company: 'Yearbook 2024',
    logo: '/images/careers/rosvo.png',
    location: 'SMAN 11 Semarang',
    type: 'Full-time',
    start_date: '2023-8',
    end_date: '2024-4',
    link: 'https://seeru.ae',
    responsibilities: [
      'Attend meetings to determine ideas, themes, and concepts for the Yearbook including packaging design.',
      'Edit and enhance photos to ensure the best quality. This includes adjusting lighting, contrast, and removing visual defects.',
      'Coordinate with the team responsible for gathering information and writing to ensure content matches the visual design.',
      'Review the entire book design to check for errors that need to be corrected before entering the final production stage.',
      'Coordinate with class representatives to check the design and layout of each class to ensure the design and layout are appropriate.',
      'Coordinate with vendors to ensure all designs and book contents are correct, and perform quality control before the book is distributed.',
    ],
  },
];
